### ISSUE TITLE
An idea how to remove skybox

### ISSUE THREAD

**Issue by Triang3l** [w23/OpenSource#11]
I have an idea how to remove the skybox areas.

First, find the leaf in which info_player_start's "eyes" are placed. Push this leaf to the stack.

Then, until the stack is empty, repeat:
1) Pop leaf from the stack.
2) Mark popped leaf.
3) For each visible leaf of that leaf:
3.1) Check if it's not already marked. Proceed to 3.2 if it's not.
3.2) Push the visible leaf to the stack.

Then, make a mesh containing only polygons from the marked leaves.

What do you think?

---

У меня есть идея, как убрать скайбоксы.

Сначала, найди тот лист, в котором находятся "глаза" info_player_start'а. Положи его на стек.

Затем, пока стек не стал пустым, выполняй следующие действия:
1) Возьми лист со стека.
2) Отметь его.
3) С каждым видимым листом у этого листа:
3.1) Проверь, не был ли он отмечен ранее. Если нет, переходи к 3.2.
3.2) Положи этот лист на стек.

Потом, сделай меш, содержащий только полигоны из отмеченных листьев.

Как тебе идея?

**Comment by w23** [comment]
Skyboxes were implemented with #25 in https://github.com/w23/OpenSource/commit/2a47e6beb1dc8dbcf29762604799d0cbd340db1f
