### ISSUE TITLE
doesn't build in VS2017

### ISSUE THREAD

**Issue by MajickTek** [w23/OpenSource#48]
The code doesn't build in VS2017 on Windows 10 Home. This is quite odd, the project should have been easy to migrate.

the include paths are not set up right (so it cant find the headers), and app_windows.c/.h are missing.

I can't wait to get this working though!

**Comment by w23** [comment]
Seems like atto submodule isn't there. Try `git submodule update --init`

**Comment by MajickTek** [comment]
Thanks a lot! I'll report back if this doesn't work.

**Comment by MajickTek** [comment]
haven't tried this yet, but i need to download git.

how could i download the dependencies without git or github desktop?

**Comment by w23** [comment]
You need to download this https://github.com/w23/atto and put it into src/atto

**Comment by MajickTek** [comment]
that's what I thought. thanks!

I might try this on a linux/Mac machine as well, with the provided makefile. not expecting it to work, but I'll give it a try!

**Comment by MajickTek** [comment]
oh. thanks anyway!

**Comment by MajickTek** [comment]
I went into VS2017 and it seemed to be working fine.

However, upon building, I got two warnings and two errors:

~~~~
Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4047	'function': 'HRAWINPUT' differs in levels of indirection from 'LPARAM'	OpenSource	c:\users\kennedy\downloads\opensource-master\opensource-master\src\atto\src\app_windows.c	322	
Warning	C4024	'GetRawInputData': different types for formal and actual parameter 1	OpenSource	c:\users\kennedy\downloads\opensource-master\opensource-master\src\atto\src\app_windows.c	322	
Error	LNK2019	unresolved external symbol glCompressedTexImage2D referenced in function renderTextureUpload	OpenSource	C:\Users\Kennedy\Downloads\OpenSource-master\OpenSource-master\render.obj	1	
Error	LNK1120	1 unresolved externals	OpenSource	C:\Users\Kennedy\Downloads\OpenSource-master\OpenSource-master\x64\Debug\OpenSource.exe	1	
~~~~

**Comment by w23** [comment]
Thank you for reporting these. I don't have a Windows machine at hand right now. Could you check that this branch https://github.com/w23/OpenSource/tree/48-fix-win-build fixes the issue?
