### ISSUE TITLE
Make public release pipeline

### ISSUE THREAD

**Issue by w23** [w23/OpenSource#54]
There are people who want to run this on their machines.
Figure out how best to make release binaries for this project for at least Windows.

**Comment by ertup0** [comment]
So, when are you gonna do that?

**Comment by w23** [comment]
🤷
This is not an active project for me right now (active hobby project now is arguably more interesting Vulkan RTX for Half-Life 1 :D).
I'm trying to allocate time to do background things occasionally, but it's slow and unpredictable.

:(

**Comment by w23** [comment]
@ertup0 hey, i finally took some time to get gh release pipeline going, and after a few iterations of massaging it a bit and trying to persuade it to do what it's supposed to do it did this (yay i guess):
https://github.com/w23/OpenSource/releases/tag/v0.0.1g

It's kind of very obnoxious and counter-intuitive to use, so I'll write down a README/tutorial tomorrow.

**Comment by ertup0** [comment]
So I'm downloaded the exe and cfg, but my steam isn't located in the default install directory. How do I specify that?

**Comment by w23** [comment]
1. Please get the latest zip release from here (if not already): https://github.com/w23/OpenSource/releases
2. Add `-s` argument before the cfg file to specify Steam dir. Full path to the `common` dir with games is expected. I.e. the default path is `C:\Program Files (x86)\Steam\steamapps\common`. The most convenient way to specify this is to modify the corresponding batch file. You should end up with a file that looks like this example (assuming `D:\Steam` is where steam is):
```hl1.bat
OpenSource.exe -s D:\Steam\steamapps\common hl1.cfg
```
