### ISSUE TITLE
sourcemods texture issues

### ISSUE THREAD

**Issue by pixelqiwi** [w23/OpenSource#80]
то ли я тупой, то ли не понимаю чего-то, но я долго и упорно жонглируя папкой с модом и путями для ехе-шника смог запустить карты из raising the bar redux, указав в батнике для запуска директорию с самим модом, чтоб программа сама подсасывала ассеты

проблема вот в чем - из-за того что у мода нет .vpk файлов с контентом, я даже не знаю как мне показать программе что оно всё в распакованном виде в папке с модом
![image](https://github.com/w23/OpenSource/assets/13924553/6a82af0c-8f57-433c-8c13-e211f941d286)
если прописать vpk-шки от хл2, то становится видно около половины текстур, но всё что добавляется модом всё равно остаётся в таком виде

сейчас кфг у меня выглядит очень скромно: 
gamedir "Half-Life 2/rtbr"

dir ""

max_maps 1

map rtbr_d1_trainstation01

батник для запуска в свою очередь выглядит так:
OpenSource.exe -d "E:\Program Files (x86)\Steam\steamapps\common\Half-Life 2\rtbr" bm.cfg

буду рад любой помощи с нормальным запуском вот этого всего

**Comment by w23** [comment]
:thinking:
Я очень давно не трогал этот проект, поэтому сейчас буду разбираться как с нуля вместе с тобой.

...
По идее этого должно быть достаточно. Более того, даже `-d` аргумент по идее не нужен -- у него в коде такой же эффект, как от `dir ""` в конфиге.
То есть 
```bm.cfg
gamedir "Half-Life 2/rtbr"
dir ""
max_maps 1
map rtbr_d1_trainstation01
```
и `OpenSource.exe bm.cfg` должно быть достаточно.

Так что либо я не помню каких-то деталей, и надо смотреть в лог (/патчить код, чтобы он больше всего выводил в лог). Либо там ресурсы как-то нестандартно лежат и надо (а) показать структуру каталогов и (б) смотреть в лог.

**Comment by w23** [comment]
Посмотрел сейчас на то, как делается для эпизодов, и могу порекомендовать попробовать вот так:
```
gamedir "Half-Life 2/hl2"
vpk "hl2_textures_dir.vpk"
vpk "hl2_misc_dir.vpk"
vpk "hl2_pak_dir.vpk"
dir ""

gamedir "Half-Life 2/rtbr"
dir ""

max_maps 1
map rtbr_d1_trainstation01
```
Почему так: ресурсы второй халвы, из впкшек или без, используются много где как базовые. Вполне возможно, что есть ещё какие-то дополнительные игрули, ресурсы от которых тоже нужны.
Там точно нет никаких впкшек от самой rtbr?

**Comment by pixelqiwi** [comment]
нет, ресурсы rtbr идут сразу распакованные по папкам (i.e. materials, models, sounds, etc), условный Garry's Mod подтягивает всё в штатном режиме

при запуске с впкшками от хл2 текстуры появляются, да, но только лишь часть

**Comment by w23** [comment]
1. В логах/консоли есть какая-нибудь инфа про то, что загрузилось, а что -- нет?
2. А если туда ресурсы от эпизодов добавить?
```bm.cfg
gamedir "Half-Life 2/hl2"
vpk "hl2_textures_dir.vpk"
vpk "hl2_misc_dir.vpk"
vpk "hl2_pak_dir.vpk"
dir ""

gamedir "Half-Life 2/episodic"
vpk "ep1_pak_dir.vpk"
dir ""

gamedir "Half-Life 2/ep2"
vpk "ep2_pak_dir.vpk"
dir ""

gamedir "Half-Life 2/rtbr"
dir ""

max_maps 1
map rtbr_d1_trainstation01
```

**Comment by pixelqiwi** [comment]
с подключением текстур из эпизодов на экране появляется вот такая интересная пелена
![OpenSource_CfzUGNWSvr](https://github.com/w23/OpenSource/assets/13924553/0cce2c33-866d-435e-a41b-03d7a9a29260)

при этом в консоли пропадают ошибки по поводу отсутствующих текстур, но появляются ошибки по поводу неизвестных шейдеров в материалах
[log.txt](https://github.com/w23/OpenSource/files/12643773/log.txt)

при этом если умудриться в таком состоянии рассмотреть карту всё равно видно что половина текстур отсутствует наряду с небом

**Comment by w23** [comment]
> с подключением текстур из эпизодов на экране появляется вот такая интересная пелена ![OpenSource_CfzUGNWSvr](https://user-images.githubusercontent.com/13924553/268529614-0cce2c33-866d-435e-a41b-03d7a9a29260.gif) [ ![OpenSource_CfzUGNWSvr](https://user-images.githubusercontent.com/13924553/268529614-0cce2c33-866d-435e-a41b-03d7a9a29260.gif) ](https://user-images.githubusercontent.com/13924553/268529614-0cce2c33-866d-435e-a41b-03d7a9a29260.gif) [ ](https://user-images.githubusercontent.com/13924553/268529614-0cce2c33-866d-435e-a41b-03d7a9a29260.gif)
> 
> при этом в консоли пропадают ошибки по поводу отсутствующих текстур, но появляются ошибки по поводу неизвестных шейдеров в материалах [log.txt](https://github.com/w23/OpenSource/files/12643773/log.txt)
> 
> при этом если умудриться в таком состоянии рассмотреть карту всё равно видно что половина текстур отсутствует наряду с небом

Ого, чёт ей серьёзно в гличт-арт поплохело.
Я посмотрю, но, наверное, уже не сегодня. Там есть какие-то неочевидные зависимости, чтобы посмотреть? Поставить hl2+ep2 и распаковать архив с модом достаточно?

**Comment by pixelqiwi** [comment]
да, хл2+еп2 должно хватить

думаю также стоит отметить что мне пришлось папку с модом перетащить в папку с хл2 (вместо /sourcemods/) потому что программа по дефолту смотрит только в /common/

**Comment by w23** [comment]
(какой кошмар я нагородил в коде этого замечательного проекта)

Вот так https://github.com/w23/OpenSource/pull/81 удалось как-то запуститься. Там всё ещё есть несколько отсутствующих текстур. Я сначала было подумал, что они вшиты в bsp файлы. Но потом посмотрел, и оказалось, что там тупо case не тот, а под линуксом файлуха чувствительная к регистру. Надо будет патчить загрузчик.
На винде по идее должно просто заработать.

Проверь, пожалуйста. Если заработает, я замержу.

**Comment by pixelqiwi** [comment]
у меня конкретно сейчас нет возможности собрать программу из исходников, можешь скинуть сразу скомпиленный ехе ветки rtbr?

**Comment by w23** [comment]
> у меня конкретно сейчас нет возможности собрать программу из исходников, можешь скинуть сразу скомпиленный ехе ветки rtbr?

https://github.com/w23/OpenSource/suites/16374263867/artifacts/935362624

Там в _запросе на вытягивание_ можно:
1. кликнуть в `Show all checks` в зелёной рамке,
2. потом на `Details` любой сборки с виндой,
3. затем в `Summary`
4. внизу будет `Artifacts`

Я пока не разобрался, можно ли сделать из PR прямую ссылку на последнюю CI сборку, чтобы вот так не играть в кликер.

**Comment by pixelqiwi** [comment]
![image](https://github.com/w23/OpenSource/assets/13924553/80d06360-1edc-4f94-8305-e261db06d7fc)
бомба

**Comment by w23** [comment]
У ряда карт нет скайбоксов в принципе. И выбор текущего скайбокса основан на ближайшей карте. Поэтому мусор показывается

**Comment by w23** [comment]
Можно ли считать эту проблему закрытой, или есть что-либо ещё?
